<a href="https://colab.research.google.com/github/sandeeppalakkal/TF2.0/blob/practice/TensorFlow_2_0_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## Static graph (TensorFlow 1.x) vs Eager execution (TensorFlow 2.0)

![alt text](https://www.tensorflow.org/images/tensors_flowing.gif)
*Image take from: https://www.tensorflow.org/guide/graphs*


## TensorFlow 1.X




### Installing TensorFlow 1.X



In [0]:
!pip install tensorflow-gpu==1.13.1

     |████████████████████████████████| 345.2MB 49kB/s 


In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.15.0'

### Variables and constants in TF 1.x

#### Variables

In [0]:
#Initialize normal Variable in tf 1.x
variable = tf.Variable([[30, 20], [10, 45]])

In [4]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32_ref>

In [5]:
#Getting shape of the variable
variable.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [6]:
#Performing addition operation on the tensor produces another tf.Tensor object
variable + 2

<tf.Tensor 'add:0' shape=(2, 2) dtype=int32>

In [7]:
#If a session is not initialized we cannot access values in the Variable/Tensor
variable.eval()

ValueError: ignored

In [8]:
#Able to slice a variable, but we are still not able to retrive values from it
variable[:1]

<tf.Tensor 'strided_slice:0' shape=(1, 2) dtype=int32>

#### Getting values from variables

In [0]:
#Initialize session
session = tf.Session()

In [0]:
#Initialize ALL variables for the session
session.run(tf.global_variables_initializer())

In [11]:
#Run the eval method on the evironment with provided session to retrive values from it
variable.eval(session)

array([[30, 20],
       [10, 45]], dtype=int32)

In [18]:
(variable).eval(session)+2

array([[32, 22],
       [12, 47]], dtype=int32)

In [26]:
variable2 = variable+2
print(variable2.get_shape())
variable2.eval(session)

(2, 2)


ValueError: ignored

#### Constants/Tensors

In [0]:
#Define a TensorFlow constant matrix
tensor = tf.constant([[23, 4], [32, 51]])

In [28]:
tensor

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [29]:
#We are still not able to get the real value without defining a session
tensor.eval()

ValueError: ignored

#### Getting values from constants

In [0]:
session = tf.Session()

In [0]:
session.run(tf.global_variables_initializer())

In [0]:
#Fatching the tensor from the tensor graph/session
tensor_value = session.run(tensor)

In [33]:
tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

## TensorFlow 2.0

### Installing TensorFlow 2.0

In [2]:
!pip install tensorflow-gpu==2.0.0

In [0]:
import tensorflow as tf
import numpy as np

In [4]:
tf.__version__

'2.0.0'

### Constants/Tensors

In [0]:
#Defining a constant in TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [5]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [6]:
#Getting shape of a tensor
tensor_20.shape

TensorShape([2, 2])

### Getting values from constants

In [7]:
#Getting values straight from a TensorFlow constant to numpy - withut sesion
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [0]:
#We are able to convert a numpy matrix back to a TensorFlow tensor as well
numpy_tensor = np.array([[23,  4], [32, 51]])

In [0]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [11]:
tensor_from_numpy

<tf.Tensor: id=2, shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

### Operations with constants/tensors

In [12]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: id=3, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Addition between scalar and tensor

In [13]:
tensor + 2

<tf.Tensor: id=5, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

#### Multiplication between scalar and tensor

In [14]:
tensor * 5

<tf.Tensor: id=7, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

#### Using Numpy functions on TensorFlow tensors

In [15]:
#Squaring all numbers in a tensorflow tensor object
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [16]:
#Square root of all numbers in a tensorflow tensor object
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Dot product between two tensors

In [17]:
 np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

### Operations with variables

In [20]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
print(tf2_variable)
print(type(tf2_variable))

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


#### Getting raw value from the variable

In [21]:
print(tf2_variable.numpy())
print(type(tf2_variable.numpy()))

[[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'>


#### Changing specific value in the TensorFlow variable

In [22]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [23]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Strings in TensorFlow 2.0

In [24]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: id=36, shape=(), dtype=string, numpy=b'TensorFlow'>

#### Simple string operations

In [25]:
tf.strings.length(tf_string)

<tf.Tensor: id=37, shape=(), dtype=int32, numpy=10>

In [26]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: id=41, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

### Storing arrays of strings

In [0]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [28]:
#How to iterate through the TF string array
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)


### Handling Devices in TensorFlow 2.0

#### CPU

In [0]:
with tf.device("/cpu:0"):
    tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [6]:
tf_string_array.device

'/job:localhost/replica:0/task:0/device:CPU:0'

#### GPU

In [8]:
if tf.test.is_gpu_available():
    with tf.device("/gpu:0"):
        tf_string_array2 = tf.constant(["TensorFlow", "Deep Learning", "AI"])
    print(tf_string_array2.device)

RuntimeError: ignored

In [10]:
if tf.test.is_gpu_available():
    with tf.device("/gpu:0"):
        tf_numbers = tf.constant([1,2,3])
    print(tf_numbers)
    print(tf_numbers.device)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
/job:localhost/replica:0/task:0/device:CPU:0
